#!/bin/sh
if [ "$(vcgencmd get_mem gpu | grep -o '[0-9]\+')" -lt 128 ]
  then
    echo -e "\033[91mWARNING: GPU MEMORY TOO LOW"
fi


udevd &
udevadm trigger

fbcp &

# Set the backlight brightness of a Raspberry touchscreen
# The environment variable RPI_BACKLIGHT can be set to a value 0-255.
export RPI_BACKLIGHT=${RPI_BACKLIGHT:-255}
if [ -f /sys/class/backlight/rpi_backlight/brightness ]; then
	echo $RPI_BACKLIGHT > /sys/class/backlight/rpi_backlight/brightness
fi

# Writable directories. See documentation here:
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export HOME=/tmp/balena
mkdir -p /tmp/balena/xdg_runtime
chmod 0700 /tmp/balena/xdg_runtime
export XDG_RUNTIME_DIR=/tmp/balena/xdg_runtime

# Enable touch screen
export WPE_BCMRPI_TOUCH=1

#Set whether to show a cursor or not
if [[ -z ${WPE_BCMRPI_CURSOR+x} ]] # don't do anything if legacy var set
  then
  if [[ ! -z $SHOW_CURSOR ]] && [[ "$SHOW_CURSOR" -eq "1" ]]
    then
      #enable cursor is new var set
      export WPE_BCMRPI_CURSOR=1
      echo "Enabling cursor"
    else
      #disable cursor if new var also not set
      unset WPE_BCMRPI_CURSOR
      echo "Disabling cursor"
  fi
fi

# Start Tohora
./tohora 8080 cog &

# wait for it
sleep 1

# Check if we have a GALLERY_URL set, otherwise load WPE_URL var
if [[ ! -z ${GALLERY_URL} ]]
  then
    echo "Loading gallery"
    WPE_URL="file:///var/lib/public_html/index.html"
fi

if [[ ! -z ${WPE_URL+x} ]]
  then
    sleep 5
    wget --post-data "url=$WPE_URL" http://localhost:8080/launch/
elif [[ ! -z ${LAUNCH_URL+x} ]]
	then
		sleep 5
    wget --post-data "url=$LAUNCH_URL" http://localhost:8080/launch/
fi

tail -f /dev/null